services:
  backend:
    image: ${DOCKER_USERNAME}/guiasai-backend:latest
    container_name: guiasai-backend-prod
    restart: unless-stopped
    environment:
      # OWASP: Explicitly enforce production checks
      - NODE_ENV=production
      # Injected safely from Dokploy's UI global variables
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://guiasai-redis:6379
    networks:
      - dokploy-network
    depends_on:
      - redis

  frontend:
    image: ${DOCKER_USERNAME}/guiasai-frontend:latest
    container_name: guiasai-frontend-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://TU_DOMINIO_DEL_BACKEND.com
    networks:
      - dokploy-network

  redis:
    image: redis:7-alpine
    container_name: guiasai-redis-prod
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - dokploy-network

volumes:
  redis_data:


networks:
  dokploy-network:
    external: true
